-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE posts (
    postid SERIAL UNIQUE PRIMARY KEY,
    amount numeric NOT NULL,
    currency character varying(5) NOT NULL,
    location character varying(50) NOT NULL,
    notes character varying(255),
    valueinusd numeric NOT NULL,
    selleremail character varying(255) NOT NULL,
    sellername character varying(200) NOT NULL,
    sellerid integer NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX posts_postid_key ON posts(postid int4_ops);
CREATE UNIQUE INDEX posts_pkey ON posts(postid int4_ops);


-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id integer DEFAULT nextval('users_userid_seq'::regclass) UNIQUE PRIMARY KEY,
    firstname character varying(200) NOT NULL,
    lastname character varying(200) NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    password character varying(255) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_userid_key ON users(id int4_ops);
CREATE UNIQUE INDEX users_email_key ON users(email text_ops);
CREATE UNIQUE INDEX users_pkey ON users(id int4_ops);
